service: mes-delegated-bookings-service

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    DELEGATED_BOOKINGS_DDB_TABLE_NAME: delegatedBookings
    DDB_OFFLINE_ENDPOINT: http://localhost:8000
    AWS_ACCESS_KEY_ID: accessKeyId
    AWS_SECRET_ACCESS_KEY: secretAccessKey

package:
  individually: true

functions:
  getDelegatedBooking:
    handler: src/functions/getDelegatedBooking/framework/handler.handler
    events:
      - http:
          path: 'delegated-bookings/{applicationReference}'
          method: get
          authorizer:
            type: CUSTOM
            authorizerId: customAuth
          localAuthorizer:
            name: LOCAL_AUTH_PROXY
            type: request

custom:
  dynamodb:
    stages:
      - dev
      - test
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    seed:
      test:
        sources:
          - table: delegatedBookings
            sources: [ ./test-data/dynamo-seed-dlg-bookings.json ]
  webpack:
    webpackConfig: 'webpack-sls-offline.config.js'

resources:
  Resources:
    delegatedBookings:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DELEGATED_BOOKINGS_DDB_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: applicationReference
            AttributeType: N
        KeySchema:
          - AttributeName: applicationReference
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

plugins:
  - serverless-offline-local-authorizers-plugin
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-dynamodb
  - serverless-offline
