service: mes-delegated-bookings-service

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    DELEGATED_BOOKING_DDB_TABLE_NAME: delegatedBookings

package:
  individually: true

functions:
  getDelegatedBooking:
    handler: src/functions/getDelegatedBooking/framework/handler.handler
    events:
      - http:
          path: 'delegated-bookings/{applicationReference}'
          method: get
          authorizer:
            type: CUSTOM
            authorizerId: some-id
          localAuthorizer:
            name: LOCAL_AUTH_PROXY
            type: request

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    seed:
      dev:
        sources:
          - table: delegated-bookings
            sources: [./test-data/dynamo-seed-dlg-bookings.json]

  webpack:
    webpackConfig: 'webpack-sls-offline.config.js'

resources:
  Resources:
    journals:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DELEGATED_BOOKING_DDB_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: applicationReference
            AttributeType: N
        KeySchema:
          - AttributeName: applicationReference
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

plugins:
  - serverless-offline-local-authorizers-plugin
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline
